pub mod affine_ops;
pub mod area;
pub mod bounding_rect;
pub mod center;
pub mod centroid;
pub mod chaikin_smoothing;
pub mod concave_hull;
pub mod contains;
pub mod convex_hull;
pub mod densify;
pub mod euclidean_distance;
pub mod frechet_distance;
pub mod has_dimensions;
pub mod interior_point;
pub mod length;
pub mod line_interpolate_point;
pub mod line_locate_point;
pub mod minimum_rotated_rect;
pub mod native;
pub mod remove_repeated_points;
pub mod rotate;
pub mod scale;
pub mod simplify;
pub mod skew;
pub mod translate;

extendr_api::extendr_module! {
    mod algorithm;
    use affine_ops;
    use area;
    use bounding_rect;
    use center;
    use centroid;
    use chaikin_smoothing;
    use concave_hull;
    use contains;
    use convex_hull;
    use densify;
    use euclidean_distance;
    use frechet_distance;
    use has_dimensions;
    use interior_point;
    use length;
    use line_interpolate_point;
    use line_locate_point;
    use minimum_rotated_rect;
    use native;
    use remove_repeated_points;
    use rotate;
    use scale;
    use simplify;
    use skew;
    use translate;
}
