# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib geoarrowrs, .registration = TRUE
NULL

#' Rotate geometries around their centroid
#'
#' Rotates each geometry counter-clockwise by `degrees` about its own centroid.
#' The geometry type of the output matches the geometry type of the input.
#'
#' @param geometry a GeoArrow point, linestring, multilinestring, polygon, or multipolygon array
#' @param degrees angle of rotation; length 1 or the same length as `geometry`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family affine
#' @references [Rotate](https://docs.rs/geo/latest/geo/algorithm/rotate/trait.Rotate.html)
rotate_around_centroid <- function(geometry, degrees) .Call(wrap__rotate_around_centroid, geometry, degrees)

#' Rotate geometries around the center of their bounding box
#'
#' Rotates each geometry counter-clockwise by `degrees` about the center of its
#' own axis-aligned bounding rectangle. The geometry type of the output matches
#' the geometry type of the input.
#'
#' @param geometry a GeoArrow point, linestring, multilinestring, polygon, or multipolygon array
#' @param degrees angle of rotation; length 1 or the same length as `geometry`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family affine
#' @references [Rotate](https://docs.rs/geo/latest/geo/algorithm/rotate/trait.Rotate.html)
rotate_around_center <- function(geometry, degrees) .Call(wrap__rotate_around_center, geometry, degrees)

#' Scale geometries independently in x and y about their centroid
#'
#' Scales each geometry by `x_factor` along the x axis and `y_factor` along the
#' y axis, about the geometry's own centroid. The geometry type of the output
#' matches the geometry type of the input.
#'
#' @param geometry a GeoArrow point, linestring, multilinestring, polygon, or multipolygon array
#' @param x_factor scaling factor along the x axis; length 1 or the same length as `geometry`
#' @param y_factor scaling factor along the y axis; length 1 or the same length as `geometry`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family affine
#' @references [Scale](https://docs.rs/geo/latest/geo/algorithm/scale/trait.Scale.html)
scale_xy <- function(geometry, x_factor, y_factor) .Call(wrap__scale_xy, geometry, x_factor, y_factor)

#' Skew geometries uniformly about their centroid
#'
#' Shears each geometry by `degrees` along both the x and y dimensions, about
#' the geometry's own centroid. The geometry type of the output matches the
#' geometry type of the input.
#'
#' @param geometry a GeoArrow point, linestring, multilinestring, polygon, or multipolygon array
#' @param degrees the shear angle; length 1 or the same length as `geometry`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family affine
#' @references [Skew](https://docs.rs/geo/latest/geo/algorithm/skew/trait.Skew.html)
skew <- function(geometry, degrees) .Call(wrap__skew, geometry, degrees)

#' Skew geometries independently in x and y about their centroid
#'
#' Shears each geometry by `degrees_x` along the x dimension and `degrees_y`
#' along the y dimension, about the geometry's own centroid. The geometry type
#' of the output matches the geometry type of the input.
#'
#' @param geometry a GeoArrow point, linestring, multilinestring, polygon, or multipolygon array
#' @param degrees_x shear angle along the x dimension; length 1 or the same length as `geometry`
#' @param degrees_y shear angle along the y dimension; length 1 or the same length as `geometry`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family affine
#' @references [Skew](https://docs.rs/geo/latest/geo/algorithm/skew/trait.Skew.html)
skew_xy <- function(geometry, degrees_x, degrees_y) .Call(wrap__skew_xy, geometry, degrees_x, degrees_y)

#' Translate geometries along the x and y axes
#'
#' Shifts every coordinate of each geometry by `x_offset` and `y_offset`. The
#' geometry type of the output matches the geometry type of the input.
#'
#' @param geometry a GeoArrow point, linestring, multilinestring, polygon, or multipolygon array
#' @param x_offset distance to shift along the x axis; length 1 or the same length as `geometry`
#' @param y_offset distance to shift along the y axis; length 1 or the same length as `geometry`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family affine
#' @references [Translate](https://docs.rs/geo/latest/geo/algorithm/translate/trait.Translate.html)
translate <- function(geometry, x_offset, y_offset) .Call(wrap__translate, geometry, x_offset, y_offset)

#' Compute the signed and unsigned planar area of geometries
#'
#' `signed_area()` returns positive values for counter-clockwise winding and
#' negative values for clockwise winding. `unsigned_area()` always returns a
#' non-negative value.
#'
#' @param x a GeoArrow geometry array
#' @returns a double vector of area values in the units of the coordinate system
#' @export
#' @rdname area
#' @family area
#' @references [Area](https://docs.rs/geo/latest/geo/algorithm/area/trait.Area.html)
signed_area <- function(x) .Call(wrap__signed_area, x)

#' @export
#' @rdname area
#' @family area
#' @references [Area](https://docs.rs/geo/latest/geo/algorithm/area/trait.Area.html)
unsigned_area <- function(x) .Call(wrap__unsigned_area, x)

#' Compute the signed and unsigned area using the Chamberlain-Duquette algorithm
#'
#' These functions use the Chamberlain-Duquette formula, which is suitable for
#' geographic coordinates on a sphere. Results are in square meters.
#'
#' @param x a GeoArrow geometry array
#' @returns a double vector of area values in square meters
#' @export
#' @rdname area_cd
#' @family area
#' @references [ChamberlainDuquetteArea](https://docs.rs/geo/latest/geo/algorithm/chamberlain_duquette_area/trait.ChamberlainDuquetteArea.html)
signed_area_cd <- function(x) .Call(wrap__signed_area_cd, x)

#' @export
#' @rdname area_cd
#' @family area
#' @references [ChamberlainDuquetteArea](https://docs.rs/geo/latest/geo/algorithm/chamberlain_duquette_area/trait.ChamberlainDuquetteArea.html)
unsigned_area_cd <- function(x) .Call(wrap__unsigned_area_cd, x)

#' Compute the signed and unsigned geodesic area and perimeter of geometries
#'
#' These functions use the geodesic formula for computing area and perimeter on
#' an ellipsoidal model of the earth. Results are in square meters for area and
#' meters for perimeter.
#'
#' @param x a GeoArrow geometry array
#' @returns a double vector of area values in square meters, or perimeter values in meters
#' @export
#' @rdname area_geodesic
#' @family area
#' @references [GeodesicArea](https://docs.rs/geo/latest/geo/algorithm/geodesic_area/trait.GeodesicArea.html)
signed_area_geodesic <- function(x) .Call(wrap__signed_area_geodesic, x)

#' @export
#' @rdname area_geodesic
#' @family area
#' @references [GeodesicArea](https://docs.rs/geo/latest/geo/algorithm/geodesic_area/trait.GeodesicArea.html)
unsigned_area_geodesic <- function(x) .Call(wrap__unsigned_area_geodesic, x)

#' @export
#' @rdname area_geodesic
#' @family area
#' @references [GeodesicArea](https://docs.rs/geo/latest/geo/algorithm/geodesic_area/trait.GeodesicArea.html)
perimeter_signed_geodesic <- function(x) .Call(wrap__perimeter_signed_geodesic, x)

#' @export
#' @rdname area_geodesic
#' @family area
#' @references [GeodesicArea](https://docs.rs/geo/latest/geo/algorithm/geodesic_area/trait.GeodesicArea.html)
perimeter_unsigned_geodesic <- function(x) .Call(wrap__perimeter_unsigned_geodesic, x)

#' Compute pairwise distances between points
#'
#' Calculate the distance between each pair of points in `origin` and `dest`.
#' These functions differ in the metric space used for the calculation.
#'
#' @param origin a GeoArrow point array of origin points
#' @param dest a GeoArrow point array of destination points
#' @returns a double vector of distance values
#' @export
#' @rdname dist_pairwise
#' @family distance
#' @references
#'   [Distance](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Distance.html),
#'   [Euclidean](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/struct.Euclidean.html)
dist_euclidean_pairwise <- function(origin, dest) .Call(wrap__dist_euclidean_pairwise, origin, dest)

#' @export
#' @rdname dist_pairwise
#' @family distance
#' @references
#'   [Distance](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Distance.html),
#'   [Haversine](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/constant.Haversine.html)
dist_haversine_pairwise <- function(origin, dest) .Call(wrap__dist_haversine_pairwise, origin, dest)

#' @export
#' @rdname dist_pairwise
#' @family distance
#' @references
#'   [Distance](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Distance.html),
#'   [Geodesic](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/static.Geodesic.html)
dist_geodesic_pairwise <- function(origin, dest) .Call(wrap__dist_geodesic_pairwise, origin, dest)

#' @export
#' @rdname dist_pairwise
#' @family distance
#' @references
#'   [Distance](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Distance.html),
#'   [Rhumb](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/struct.Rhumb.html)
dist_rhumb_pairwise <- function(origin, dest) .Call(wrap__dist_rhumb_pairwise, origin, dest)

#' Compute the pairwise Hausdorff distance between geometries
#'
#' The Hausdorff distance measures how far two geometries are from each other
#' by taking the maximum of all minimum distances between points on the two shapes.
#'
#' @param origin a GeoArrow geometry array
#' @param dest a GeoArrow geometry array
#' @returns a double vector of Hausdorff distance values
#' @export
#' @family distance
#' @references [HausdorffDistance](https://docs.rs/geo/latest/geo/algorithm/hausdorff_distance/trait.HausdorffDistance.html)
dist_hausdorff_pairwise <- function(origin, dest) .Call(wrap__dist_hausdorff_pairwise, origin, dest)

#' Compute the pairwise Vincenty distance between points
#'
#' The Vincenty formula computes the geodesic distance between two points on
#' an ellipsoidal model of the earth. Returns `NA` if the algorithm fails to
#' converge.
#'
#' @param origin a GeoArrow point array of origin points
#' @param dest a GeoArrow point array of destination points
#' @returns a double vector of distance values in meters
#' @export
#' @family distance
#' @references [VincentyDistance](https://docs.rs/geo/latest/geo/algorithm/vincenty_distance/trait.VincentyDistance.html)
dist_vincenty_pairwise <- function(origin, dest) .Call(wrap__dist_vincenty_pairwise, origin, dest)

#' Compute the pairwise Frechet distance between linestrings
#'
#' The Frechet distance measures the similarity between two curves by
#' considering the location and ordering of points along each curve.
#' Uses the Euclidean metric.
#'
#' @param origin a GeoArrow linestring array
#' @param dest a GeoArrow linestring array
#' @returns a double vector of Frechet distance values
#' @export
#' @family distance
#' @references [FrechetDistance](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.FrechetDistance.html)
dist_frechet_pairwise <- function(origin, dest) .Call(wrap__dist_frechet_pairwise, origin, dest)

#' Collect a geometry's coordinates as points
#'
#' Returns one multipoint per input geometry, holding that geometry's
#' vertices in order. The output has the same length as the input.
#'
#' @details
#' `exterior_coords()` skips the interior rings of a polygon, so it gives the
#' outline only. Both preserve the order the coordinates are stored in, so a
#' closed ring repeats its first vertex at the end.
#'
#' A null geometry stays null.
#'
#' @param geometry a GeoArrow geometry array
#' @returns a GeoArrow multipoint array of the same length as `geometry`
#' @export
#' @rdname coords
#' @family iteration
#' @references [CoordsIter](https://docs.rs/geo/latest/geo/algorithm/coords_iter/trait.CoordsIter.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' ring <- matrix(c(0, 0, 2, 0, 2, 2, 0, 2, 0, 0), ncol = 2, byrow = TRUE)
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_polygon(list(ring))))
#'
#' sf::st_as_sfc(geoarrow::as_geoarrow_vctr(coords(g)))
#' as.vector(nanoarrow::convert_array(n_coords(g)))
coords <- function(geometry) .Call(wrap__coords, geometry)

#' @export
#' @rdname coords
#' @family iteration
exterior_coords <- function(geometry) .Call(wrap__exterior_coords, geometry)

#' Count the coordinates in each geometry
#'
#' Returns how many vertices each geometry holds.
#'
#' @details
#' Counts every coordinate that [coords()] would return, so a closed ring
#' counts its repeated final vertex. A null geometry gives `NA`.
#'
#' @param geometry a GeoArrow geometry array
#' @returns an integer array of the same length as `geometry`
#' @export
#' @family iteration
#' @references [CoordsIter](https://docs.rs/geo/latest/geo/algorithm/coords_iter/trait.CoordsIter.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' ring <- matrix(c(0, 0, 2, 0, 2, 2, 0, 2, 0, 0), ncol = 2, byrow = TRUE)
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_polygon(list(ring))))
#'
#' as.vector(nanoarrow::convert_array(n_coords(g)))
n_coords <- function(geometry) .Call(wrap__n_coords, geometry)

#' Split geometries into their line segments
#'
#' Returns one multilinestring per input geometry, whose parts are that
#' geometry's two point segments. The output has the same length as the input.
#'
#' @details
#' A polygon contributes the segments of every ring, interior rings included.
#' A point has no segments and becomes a null element, as does a null
#' geometry.
#'
#' @param geometry a GeoArrow geometry array
#' @returns a GeoArrow multilinestring array of the same length as `geometry`
#' @export
#' @family iteration
#' @references [LinesIter](https://docs.rs/geo/latest/geo/algorithm/lines_iter/trait.LinesIter.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' ring <- matrix(c(0, 0, 2, 0, 2, 2, 0, 2, 0, 0), ncol = 2, byrow = TRUE)
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_polygon(list(ring))))
#'
#' lengths(sf::st_as_sfc(geoarrow::as_geoarrow_vctr(lines(g))))
lines <- function(geometry) .Call(wrap__lines, geometry)

#' Compute the length of linestrings
#'
#' These functions calculate the total length of each linestring using
#' different metric spaces. Use the geodesic or haversine variants for
#' geographic coordinates, and euclidean for projected coordinates.
#'
#' @param x a GeoArrow linestring array
#' @returns a double vector of length values
#' @export
#' @rdname length
#' @family length
#' @references
#'   [Length](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Length.html),
#'   [Euclidean](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/struct.Euclidean.html)
length_euclidean <- function(x) .Call(wrap__length_euclidean, x)

#' @export
#' @rdname length
#' @family length
#' @references
#'   [Length](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Length.html),
#'   [Haversine](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/constant.Haversine.html)
length_haversine <- function(x) .Call(wrap__length_haversine, x)

#' @export
#' @rdname length
#' @family length
#' @references
#'   [Length](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Length.html),
#'   [Geodesic](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/static.Geodesic.html)
length_geodesic <- function(x) .Call(wrap__length_geodesic, x)

#' @export
#' @rdname length
#' @family length
#' @references
#'   [Length](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Length.html),
#'   [Rhumb](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/struct.Rhumb.html)
length_rhumb <- function(x) .Call(wrap__length_rhumb, x)

#' Compute the Vincenty length of linestrings or multilinestrings
#'
#' Calculates the geodesic length of each linestring or multilinestring using
#' the Vincenty formula on an ellipsoidal model of the earth. Returns `NA`
#' if the algorithm fails to converge. Results are in meters.
#'
#' @param x a GeoArrow linestring or multilinestring array
#' @returns a double vector of length values in meters
#' @export
#' @rdname length
#' @family length
#' @references [VincentyLength](https://docs.rs/geo/latest/geo/algorithm/vincenty_length/trait.VincentyLength.html)
length_vincenty <- function(x) .Call(wrap__length_vincenty, x)

#' Compute the bearing between pairs of points
#'
#' Calculate the bearing in degrees from `origin` to `dest` for each pair of
#' points. Bearing is measured clockwise from north (0 degrees) to 360 degrees.
#' These functions differ in the metric space used for the calculation.
#'
#' @param origin a GeoArrow point array of origin points
#' @param dest a GeoArrow point array of destination points
#' @returns a double vector of bearing values in degrees
#' @export
#' @rdname bearing
#' @family bearing
#' @references
#'   [Bearing](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Bearing.html),
#'   [Euclidean](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/struct.Euclidean.html)
bearing_euclidean <- function(origin, dest) .Call(wrap__bearing_euclidean, origin, dest)

#' @export
#' @rdname bearing
#' @family bearing
#' @references
#'   [Bearing](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Bearing.html),
#'   [Haversine](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/constant.Haversine.html)
bearing_haversine <- function(origin, dest) .Call(wrap__bearing_haversine, origin, dest)

#' @export
#' @rdname bearing
#' @family bearing
#' @references
#'   [Bearing](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Bearing.html),
#'   [Geodesic](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/static.Geodesic.html)
bearing_geodesic <- function(origin, dest) .Call(wrap__bearing_geodesic, origin, dest)

#' @export
#' @rdname bearing
#' @family bearing
#' @references
#'   [Bearing](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Bearing.html),
#'   [Rhumb](https://docs.rs/geo/latest/geo/algorithm/line_measures/metric_spaces/struct.Rhumb.html)
bearing_rhumb <- function(origin, dest) .Call(wrap__bearing_rhumb, origin, dest)

#' Compute a destination point from an origin, bearing, and distance
#'
#' Returns the point reached by travelling `distance` from `origin` along
#' `bearing`. Each function uses a different metric space: `dest_euclidean`
#' treats coordinates as planar, `dest_haversine` assumes a sphere,
#' `dest_geodesic` an ellipsoid, and `dest_rhumb` follows a line of constant
#' bearing.
#'
#' @param origin a GeoArrow point array
#' @param bearing a numeric vector of bearings in degrees; length 1 or the same length as `origin`
#' @param distance a numeric vector of distances; length 1 or the same length as `origin`
#' @returns a GeoArrow point array
#' @export
#' @rdname destination
#' @family destination
#' @references [Destination](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Destination.html)
dest_rhumb <- function(origin, bearing, distance) .Call(wrap__dest_rhumb, origin, bearing, distance)

#' @export
#' @rdname destination
dest_euclidean <- function(origin, bearing, distance) .Call(wrap__dest_euclidean, origin, bearing, distance)

#' @export
#' @rdname destination
dest_haversine <- function(origin, bearing, distance) .Call(wrap__dest_haversine, origin, bearing, distance)

#' @export
#' @rdname destination
dest_geodesic <- function(origin, bearing, distance) .Call(wrap__dest_geodesic, origin, bearing, distance)

#' Find the point on a geometry closest to another point
#'
#' Returns the position on each geometry nearest the corresponding point,
#' using planar distance. `closest_point_haversine()` measures on a sphere
#' instead, treating coordinates as longitude and latitude in degrees.
#'
#' @details
#' When the point lies on the geometry the intersection itself is returned.
#' A geometry with no single nearest position, such as a point equidistant
#' from both ends of a symmetric line, becomes a null element, as does a null
#' geometry or a null point.
#'
#' @param geometry a GeoArrow geometry array
#' @param point a GeoArrow point array; length 1 or the same length as `geometry`
#' @returns a GeoArrow point array of the same length as `geometry`
#' @export
#' @rdname closest_point
#' @family query
#' @references [ClosestPoint](https://docs.rs/geo/latest/geo/algorithm/closest_point/trait.ClosestPoint.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' line <- geoarrow::as_geoarrow_array(sf::st_sfc(
#'   sf::st_linestring(cbind(c(0, 10), c(0, 0)))
#' ))
#' pt <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_point(c(4, 5))))
#'
#' sf::st_as_sfc(geoarrow::as_geoarrow_vctr(closest_point(line, pt)))
closest_point <- function(geometry, point) .Call(wrap__closest_point, geometry, point)

#' @export
#' @rdname closest_point
#' @family query
#' @references [HaversineClosestPoint](https://docs.rs/geo/latest/geo/algorithm/haversine_closest_point/trait.HaversineClosestPoint.html)
closest_point_haversine <- function(geometry, point) .Call(wrap__closest_point_haversine, geometry, point)

#' Compute a representative point inside a geometry
#'
#' Returns a point guaranteed to lie on the geometry, unlike [centroid()],
#' which can fall outside a concave shape.
#'
#' @details
#' For a polygon this is a point on the interior, chosen from the horizontal
#' line closest to the centroid. An empty or null geometry becomes a null
#' element.
#'
#' @param geometry a GeoArrow geometry array
#' @returns a GeoArrow point array of the same length as `geometry`
#' @export
#' @family query
#' @references [InteriorPoint](https://docs.rs/geo/latest/geo/algorithm/interior_point/trait.InteriorPoint.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_polygon(list(
#'   matrix(c(0, 0, 4, 0, 4, 4, 0, 4, 0, 0), ncol = 2, byrow = TRUE)
#' ))))
#'
#' sf::st_as_sfc(geoarrow::as_geoarrow_vctr(interior_point(g)))
interior_point <- function(geometry) .Call(wrap__interior_point, geometry)

#' Test whether a ring is convex
#'
#' `TRUE` when the geometry's ring turns consistently in one direction. A
#' polygon is judged on its exterior ring.
#'
#' @details
#' A linestring must be closed, that is form a ring, to be reported convex; an
#' open one is `FALSE`. A polygon's exterior ring is always closed, so polygons
#' need no special handling. Any other geometry type, or a null geometry,
#' becomes `NA` rather than `FALSE`.
#'
#' @param geometry a GeoArrow linestring or polygon array
#' @returns a boolean array of the same length as `geometry`
#' @export
#' @family query
#' @references [IsConvex](https://docs.rs/geo/latest/geo/algorithm/is_convex/trait.IsConvex.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' square <- sf::st_polygon(list(
#'   matrix(c(0, 0, 1, 0, 1, 1, 0, 1, 0, 0), ncol = 2, byrow = TRUE)
#' ))
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(square))
#'
#' as.vector(nanoarrow::convert_array(is_convex(g)))
is_convex <- function(geometry) .Call(wrap__is_convex, geometry)

#' Locate a point along a line as a fraction of its length
#'
#' Returns how far along each line the closest position to the corresponding
#' point lies, as a fraction between 0 and 1.
#'
#' @details
#' 0 is the start of the line and 1 its end, so the value multiplied by the
#' line's length gives a distance. Only lines and linestrings can be located
#' along; any other geometry type, a null geometry, a null point, or a
#' zero length line becomes `NA`.
#'
#' @param geometry a GeoArrow linestring array
#' @param point a GeoArrow point array; length 1 or the same length as `geometry`
#' @returns a double array of the same length as `geometry`
#' @export
#' @family query
#' @references [LineLocatePoint](https://docs.rs/geo/latest/geo/algorithm/line_locate_point/trait.LineLocatePoint.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' line <- geoarrow::as_geoarrow_array(sf::st_sfc(
#'   sf::st_linestring(cbind(c(0, 10), c(0, 0)))
#' ))
#' pt <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_point(c(2.5, 0))))
#'
#' as.vector(nanoarrow::convert_array(line_locate_point(line, pt)))
line_locate_point <- function(geometry, point) .Call(wrap__line_locate_point, geometry, point)

#' Simplify geometries using the Ramer-Douglas-Peucker algorithm
#'
#' Reduces the number of points in each geometry by removing vertices that
#' deviate less than `epsilon` from the simplified path. Accepts linestrings,
#' multilinestrings, polygons, and multipolygons.
#'
#' @param geometry a GeoArrow linestring, multilinestring, polygon, or multipolygon array
#' @param epsilon the simplification tolerance; length 1 or the same length as `geometry`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family simplify
#' @references [Simplify](https://docs.rs/geo/latest/geo/algorithm/simplify/trait.Simplify.html)
simplify <- function(geometry, epsilon) .Call(wrap__simplify, geometry, epsilon)

#' Simplify geometries using the Visvalingam-Whyatt algorithm
#'
#' Reduces the number of points in each geometry by removing vertices whose
#' effective area is below `epsilon`. Accepts linestrings, multilinestrings,
#' polygons, and multipolygons.
#'
#' @param geometry a GeoArrow linestring, multilinestring, polygon, or multipolygon array
#' @param epsilon the simplification tolerance; length 1 or the same length as `geometry`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @rdname simplify_vw
#' @family simplify
#' @references [SimplifyVw](https://docs.rs/geo/latest/geo/algorithm/simplify_vw/trait.SimplifyVw.html)
simplify_vw <- function(geometry, epsilon) .Call(wrap__simplify_vw, geometry, epsilon)

#' Simplify geometries using the topology-preserving Visvalingam-Whyatt algorithm
#'
#' Like `simplify_vw()` but preserves topology by preventing self-intersections
#' during simplification. Accepts linestrings, multilinestrings, polygons, and
#' multipolygons.
#'
#' @param geometry a GeoArrow linestring, multilinestring, polygon, or multipolygon array
#' @param epsilon the simplification tolerance; length 1 or the same length as `geometry`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @rdname simplify_vw
#' @family simplify
#' @references [SimplifyVwPreserve](https://docs.rs/geo/latest/geo/algorithm/simplify_vw/trait.SimplifyVwPreserve.html)
simplify_vw_preserve <- function(geometry, epsilon) .Call(wrap__simplify_vw_preserve, geometry, epsilon)

#' Test a topological relationship between two geometry arrays
#'
#' Each function compares `x` and `y` row by row and returns `TRUE` when the
#' named DE-9IM relationship holds. `y` is recycled against `x`.
#'
#' @details
#' `contains()` is `TRUE` when no point of `y` lies outside `x` and at least
#' one point of `y` lies in the interior of `x`. `within()` is the same test
#' with the arguments swapped. `covers()` and `covered_by()` are the weaker
#' forms that allow every shared point to lie on the boundary.
#' `contains_properly()` is the stricter form requiring `y` to fall entirely
#' within the interior.
#'
#' `intersects()` and `disjoint()` are negations of one another.
#' `touches()` is `TRUE` when the geometries share a boundary point but no
#' interior point, `crosses()` when their interiors meet in a lower dimension
#' than at least one of them, and `overlaps()` when they meet in the same
#' dimension as both. `equals_topo()` compares point sets rather than
#' coordinate order, so two geometries wound differently are still equal.
#'
#' A null geometry on either side gives `NA`.
#'
#' @param x a GeoArrow geometry array
#' @param y a GeoArrow geometry array; length 1 or the same length as `x`
#' @returns a boolean array of the same length as `x`
#' @export
#' @rdname topology
#' @family topology
#' @references [Relate](https://docs.rs/geo/latest/geo/algorithm/relate/trait.Relate.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' big <- sf::st_polygon(list(
#'   matrix(c(0, 0, 4, 0, 4, 4, 0, 4, 0, 0), ncol = 2, byrow = TRUE)
#' ))
#' x <- geoarrow::as_geoarrow_array(sf::st_sfc(big))
#' y <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_point(c(2, 2))))
#'
#' as.vector(nanoarrow::convert_array(contains(x, y)))
#' as.vector(nanoarrow::convert_array(intersects(x, y)))
contains <- function(x, y) .Call(wrap__contains, x, y)

#' @export
#' @rdname topology
#' @family topology
contains_properly <- function(x, y) .Call(wrap__contains_properly, x, y)

#' @export
#' @rdname topology
#' @family topology
within <- function(x, y) .Call(wrap__within, x, y)

#' @export
#' @rdname topology
#' @family topology
covers <- function(x, y) .Call(wrap__covers, x, y)

#' @export
#' @rdname topology
#' @family topology
covered_by <- function(x, y) .Call(wrap__covered_by, x, y)

#' @export
#' @rdname topology
#' @family topology
intersects <- function(x, y) .Call(wrap__intersects, x, y)

#' @export
#' @rdname topology
#' @family topology
disjoint <- function(x, y) .Call(wrap__disjoint, x, y)

#' @export
#' @rdname topology
#' @family topology
touches <- function(x, y) .Call(wrap__touches, x, y)

#' @export
#' @rdname topology
#' @family topology
crosses <- function(x, y) .Call(wrap__crosses, x, y)

#' @export
#' @rdname topology
#' @family topology
overlaps <- function(x, y) .Call(wrap__overlaps, x, y)

#' @export
#' @rdname topology
#' @family topology
equals_topo <- function(x, y) .Call(wrap__equals_topo, x, y)

#' Compute the DE-9IM relationship between two geometry arrays
#'
#' Returns the nine character DE-9IM matrix describing how each pair of
#' geometries relates, from which every named predicate can be derived.
#'
#' @details
#' The string reads as the intersections of the interior, boundary and
#' exterior of `x` with those of `y`, in that order. Each character is the
#' dimension of that intersection: `F` for empty, `0` for a point, `1` for a
#' curve, and `2` for a surface. A null geometry on either side gives `NA`.
#'
#' @inheritParams contains
#' @returns a string array of the same length as `x`
#' @export
#' @family topology
#' @references [Relate](https://docs.rs/geo/latest/geo/algorithm/relate/trait.Relate.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' big <- sf::st_polygon(list(
#'   matrix(c(0, 0, 4, 0, 4, 4, 0, 4, 0, 0), ncol = 2, byrow = TRUE)
#' ))
#' x <- geoarrow::as_geoarrow_array(sf::st_sfc(big))
#' y <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_point(c(2, 2))))
#'
#' as.vector(nanoarrow::convert_array(relate(x, y)))
relate <- function(x, y) .Call(wrap__relate, x, y)

#' Determine the topological dimension of geometries
#'
#' Returns 0 for points, 1 for lines and curves, and 2 for surfaces.
#'
#' @details
#' An empty geometry has no dimension and gives `NA`, which is distinct from a
#' point's 0. `boundary_dimension()` gives the dimension of the geometry's
#' boundary instead, so a polygon is 1 and a point is `NA`.
#'
#' @param geometry a GeoArrow geometry array
#' @returns an integer array of the same length as `geometry`
#' @export
#' @rdname dimension
#' @family topology
#' @references [HasDimensions](https://docs.rs/geo/latest/geo/algorithm/dimensions/trait.HasDimensions.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(
#'   sf::st_point(c(0, 0)),
#'   sf::st_linestring(cbind(c(0, 1), c(0, 1)))
#' ))
#'
#' as.vector(nanoarrow::convert_array(dimension(g)))
dimension <- function(geometry) .Call(wrap__dimension, geometry)

#' @export
#' @rdname dimension
#' @family topology
boundary_dimension <- function(geometry) .Call(wrap__boundary_dimension, geometry)

#' Test whether geometries are empty
#'
#' `TRUE` when the geometry holds no coordinates.
#'
#' @details
#' An empty geometry is distinct from a null one. A null geometry gives `NA`.
#'
#' @param geometry a GeoArrow geometry array
#' @returns a boolean array of the same length as `geometry`
#' @export
#' @family topology
#' @references [HasDimensions](https://docs.rs/geo/latest/geo/algorithm/dimensions/trait.HasDimensions.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(
#'   sf::st_point(c(0, 0)),
#'   sf::st_point()
#' ))
#'
#' as.vector(nanoarrow::convert_array(is_empty(g)))
is_empty <- function(geometry) .Call(wrap__is_empty, geometry)

#' Locate a point relative to a geometry
#'
#' Returns `"inside"`, `"outside"`, or `"boundary"` for each pair.
#'
#' @details
#' This is the three way form of a point in polygon test, distinguishing a
#' point that lies exactly on an edge from one strictly inside. `point` is
#' recycled against `geometry`. A null geometry or a null point gives `NA`.
#'
#' @param geometry a GeoArrow geometry array
#' @param point a GeoArrow point array; length 1 or the same length as `geometry`
#' @returns a string array of the same length as `geometry`
#' @export
#' @family topology
#' @references [CoordinatePosition](https://docs.rs/geo/latest/geo/algorithm/coordinate_position/trait.CoordinatePosition.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' square <- sf::st_polygon(list(
#'   matrix(c(0, 0, 4, 0, 4, 4, 0, 4, 0, 0), ncol = 2, byrow = TRUE)
#' ))
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(square, square, square))
#' p <- geoarrow::as_geoarrow_array(sf::st_sfc(
#'   sf::st_point(c(2, 2)), sf::st_point(c(0, 2)), sf::st_point(c(9, 9))
#' ))
#'
#' as.vector(nanoarrow::convert_array(coordinate_position(g, p)))
coordinate_position <- function(geometry, point) .Call(wrap__coordinate_position, geometry, point)

#' Triangulate polygons with the earcut algorithm
#'
#' Returns one multipolygon per input geometry, whose parts are that
#' geometry's triangles. The output has the same length as the input, so a
#' triangulated geometry stays aligned with the row it came from.
#'
#' @details
#' Earcut is defined for polygons only. A multipolygon is triangulated part by
#' part and the triangles are merged into a single multipolygon. Any other
#' geometry type, a null geometry, or a polygon that cannot be triangulated
#' becomes a null element.
#'
#' Earcut is fast and respects interior rings, but the triangles it produces
#' are not Delaunay. Use [triangulate_delaunay()] when triangle quality
#' matters.
#'
#' @param x a GeoArrow polygon or multipolygon array
#' @returns a GeoArrow multipolygon array of the same length as `x`
#' @export
#' @family triangulate
#' @references [TriangulateEarcut](https://docs.rs/geo/latest/geo/algorithm/triangulate_earcut/trait.TriangulateEarcut.html)
triangulate_earcut <- function(x) .Call(wrap__triangulate_earcut, x)

#' Triangulate geometries with a Delaunay triangulation
#'
#' Returns one multipolygon per input geometry, whose parts are that
#' geometry's triangles. The output has the same length as the input.
#'
#' @details
#' A constrained triangulation keeps the input's edges and returns only the
#' triangles that fall inside the geometry. An unconstrained triangulation
#' triangulates the convex hull of the input's vertices, ignoring its edges,
#' so it may cross holes and concavities.
#'
#' A null geometry, or one that cannot be triangulated, becomes a null
#' element.
#'
#' @param x a GeoArrow geometry array
#' @param constrained whether to constrain the triangulation to the input's
#'   edges. `TRUE` by default
#' @param snap_radius coordinates closer together than this are snapped to the
#'   same position; length 1 or the same length as `x`. `geo` uses 1e-4 by
#'   default
#' @returns a GeoArrow multipolygon array of the same length as `x`
#' @export
#' @family triangulate
#' @references [TriangulateDelaunay](https://docs.rs/geo/latest/geo/algorithm/triangulate_delaunay/trait.TriangulateDelaunay.html)
triangulate_delaunay <- function(x, constrained = TRUE, snap_radius = 1e-4) .Call(wrap__triangulate_delaunay, x, constrained, snap_radius)

#' Buffer geometries by a given distance
#'
#' Expands each geometry outward by `distance` to produce a multipolygon.
#' Line cap and join styles control the shape of the buffer at endpoints and
#' corners.
#'
#' @param geometry a GeoArrow geometry array
#' @param distance a numeric vector of buffer distances; length 1 or the same length as `geometry`
#' @param line_cap one of `"round"`, `"square"`, or `"butt"`
#' @param line_join one of `"round"`, `"miter"`, or `"bevel"`
#' @param miter_limit the miter limit used when `line_join` is `"miter"`
#' @param round_segments the number of segments used to approximate curves when `line_cap` or `line_join` is `"round"`
#' @returns a GeoArrow multipolygon array
#' @export
#' @family misc
#' @references [Buffer](https://docs.rs/geo/latest/geo/algorithm/buffer/trait.Buffer.html)
buffer <- function(geometry, distance, line_cap, line_join, miter_limit, round_segments) .Call(wrap__buffer, geometry, distance, line_cap, line_join, miter_limit, round_segments)

#' Compute the centroid of geometries
#'
#' Returns the centroid point of each geometry. Returns `NA` for empty geometries.
#'
#' @param x a GeoArrow geometry array
#' @returns a GeoArrow point array
#' @export
#' @family misc
#' @references [Centroid](https://docs.rs/geo/latest/geo/algorithm/centroid/trait.Centroid.html)
centroid <- function(x) .Call(wrap__centroid, x)

#' Smooth geometries using the Chaikin algorithm
#'
#' Applies Chaikin's corner-cutting algorithm for the given number of iterations
#' to produce smoother curves. Accepts linestrings, multilinestrings, polygons,
#' and multipolygons.
#'
#' @param geometry a GeoArrow linestring, multilinestring, polygon, or multipolygon array
#' @param n_iterations the number of smoothing iterations to apply; must be greater than 0
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family misc
#' @references [ChaikinSmoothing](https://docs.rs/geo/latest/geo/algorithm/chaikin_smoothing/trait.ChaikinSmoothing.html)
chaikin_smoothing <- function(geometry, n_iterations) .Call(wrap__chaikin_smoothing, geometry, n_iterations)

#' Remove repeated consecutive points from geometries
#'
#' Removes consecutive duplicate coordinates from each geometry. Accepts
#' linestrings, multilinestrings, polygons, and multipolygons.
#'
#' @param geometry a GeoArrow linestring, multilinestring, polygon, or multipolygon array
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family misc
#' @references [RemoveRepeatedPoints](https://docs.rs/geo/latest/geo/algorithm/remove_repeated_points/trait.RemoveRepeatedPoints.html)
remove_repeated_points <- function(geometry) .Call(wrap__remove_repeated_points, geometry)

#' Split linestrings into a given number of equal-length segments
#'
#' Divides each linestring into `segment_count` segments of equal length,
#' returning a multilinestring. Returns `NA` if segmentation fails.
#' `line_segmentize_haversine()` uses the Haversine formula for geographic
#' coordinates; `line_segmentize()` uses planar Euclidean distance.
#'
#' @param geometry a GeoArrow linestring array
#' @param segment_count the number of segments to split each linestring into; must be greater than 0
#' @returns a GeoArrow multilinestring array
#' @export
#' @rdname line_segmentize
#' @family misc
#' @references [LineStringSegmentize](https://docs.rs/geo/latest/geo/algorithm/linestring_segment/trait.LineStringSegmentize.html)
line_segmentize <- function(geometry, segment_count) .Call(wrap__line_segmentize, geometry, segment_count)

#' @export
#' @rdname line_segmentize
#' @family misc
#' @references [LineStringSegmentizeHaversine](https://docs.rs/geo/latest/geo/algorithm/linestring_segment/trait.LineStringSegmentizeHaversine.html)
line_segmentize_haversine <- function(geometry, segment_count) .Call(wrap__line_segmentize_haversine, geometry, segment_count)

#' Combine two polygon arrays with a set operation
#'
#' Each function pairs `x` with `y` row by row and returns the polygonal
#' result. `y` is recycled against `x`.
#'
#' @details
#' `boolean_intersection()` keeps the area in both, `boolean_union()` the area
#' in either, `boolean_difference()` the area in `x` but not `y`, and
#' `boolean_xor()` the area in exactly one of them.
#'
#' These are defined for polygons and multipolygons only. A row whose geometry
#' is any other type, or is null, comes back null. The result is always a
#' multipolygon, since a set operation can split one polygon into several or
#' erase it entirely.
#'
#' @param x a GeoArrow polygon or multipolygon array
#' @param y a GeoArrow polygon or multipolygon array; length 1 or the same
#'   length as `x`
#' @returns a GeoArrow multipolygon array of the same length as `x`
#' @export
#' @rdname boolean_ops
#' @family boolean
#' @references [BooleanOps](https://docs.rs/geo/latest/geo/algorithm/bool_ops/trait.BooleanOps.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' bx <- function(a, b, c, d) sf::st_polygon(list(matrix(
#'   c(a, b, c, b, c, d, a, d, a, b), ncol = 2, byrow = TRUE
#' )))
#' x <- geoarrow::as_geoarrow_array(sf::st_sfc(bx(0, 0, 2, 2)))
#' y <- geoarrow::as_geoarrow_array(sf::st_sfc(bx(1, 1, 3, 3)))
#'
#' sf::st_area(sf::st_as_sfc(geoarrow::as_geoarrow_vctr(
#'   boolean_intersection(x, y)
#' )))
boolean_intersection <- function(x, y) .Call(wrap__boolean_intersection, x, y)

#' @export
#' @rdname boolean_ops
#' @family boolean
boolean_union <- function(x, y) .Call(wrap__boolean_union, x, y)

#' @export
#' @rdname boolean_ops
#' @family boolean
boolean_difference <- function(x, y) .Call(wrap__boolean_difference, x, y)

#' @export
#' @rdname boolean_ops
#' @family boolean
boolean_xor <- function(x, y) .Call(wrap__boolean_xor, x, y)

#' Dissolve an entire array of polygons into one
#'
#' Merges every polygon in `x` into a single multipolygon, dropping the
#' boundaries between any that touch or overlap.
#'
#' @details
#' This is the one function in the package that is not length-preserving. It
#' is an aggregate over the whole array, so it always returns a length 1
#' array, in the way `sum()` reduces a vector to a single value.
#'
#' It is far faster than folding [boolean_union()] across the array, since it
#' unions all the rings in one pass. Rows that are not polygonal, and null
#' rows, are skipped.
#'
#' @param x a GeoArrow polygon or multipolygon array
#' @returns a GeoArrow multipolygon array of length 1
#' @export
#' @family boolean
#' @references [unary_union](https://docs.rs/geo/latest/geo/algorithm/bool_ops/fn.unary_union.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' bx <- function(a, b, c, d) sf::st_polygon(list(matrix(
#'   c(a, b, c, b, c, d, a, d, a, b), ncol = 2, byrow = TRUE
#' )))
#' x <- geoarrow::as_geoarrow_array(sf::st_sfc(bx(0, 0, 2, 2), bx(1, 1, 3, 3)))
#'
#' sf::st_area(sf::st_as_sfc(geoarrow::as_geoarrow_vctr(unary_union(x))))
unary_union <- function(x) .Call(wrap__unary_union, x)

#' Compute the axis-aligned bounding rectangle of geometries
#'
#' Returns the smallest axis-aligned rectangle that contains each geometry.
#'
#' @param x a GeoArrow geometry array
#' @returns a GeoArrow rect array
#' @export
#' @family boundary
#' @references [BoundingRect](https://docs.rs/geo/latest/geo/algorithm/bounding_rect/trait.BoundingRect.html)
bounding_rect <- function(x) .Call(wrap__bounding_rect, x)

#' Compute the minimum rotated bounding rectangle of geometries
#'
#' Returns the smallest rectangle of arbitrary rotation that contains each
#' geometry, as a polygon array.
#'
#' @param x a GeoArrow geometry array
#' @returns a GeoArrow polygon array
#' @export
#' @family boundary
#' @references [MinimumRotatedRect](https://docs.rs/geo/latest/geo/algorithm/minimum_rotated_rect/trait.MinimumRotatedRect.html)
minimum_rotated_rect <- function(x) .Call(wrap__minimum_rotated_rect, x)

#' Compute the convex hull of geometries
#'
#' Returns the smallest convex polygon that contains each geometry.
#'
#' @param x a GeoArrow geometry array
#' @returns a GeoArrow polygon array
#' @export
#' @family boundary
#' @references [ConvexHull](https://docs.rs/geo/latest/geo/algorithm/convex_hull/trait.ConvexHull.html)
convex_hull <- function(x) .Call(wrap__convex_hull, x)

#' Compute the concave hull of geometries
#'
#' Returns a polygon enclosing each geometry, tightened toward the geometry's
#' own shape. Smaller `concavity` values produce a tighter, more concave hull;
#' larger values approach the convex hull.
#'
#' Accepts multipoints, linestrings, multilinestrings, polygons, and
#' multipolygons. `geo` does not define a concave hull for a single point.
#'
#' @param geometry a GeoArrow multipoint, linestring, multilinestring, polygon, or multipolygon array
#' @param concavity the concavity coefficient; length 1 or the same length as `geometry`. `geo` uses 2 by default
#' @param length_threshold edges shorter than this are not considered for further refinement; length 1 or the same length as `geometry`. `geo` uses 0 by default
#' @returns a GeoArrow polygon array
#' @export
#' @family boundary
#' @references [ConcaveHull](https://docs.rs/geo/latest/geo/algorithm/concave_hull/trait.ConcaveHull.html)
concave_hull <- function(geometry, concavity, length_threshold) .Call(wrap__concave_hull, geometry, concavity, length_threshold)

#' Compute the extreme coordinates of geometries
#'
#' Returns a struct array with four point fields -- `x_min`, `x_max`, `y_min`
#' and `y_max` -- giving the coordinate that is furthest in each direction. The
#' result has one row per input geometry; a null or empty geometry yields a row
#' of four nulls.
#'
#' Note these are the extreme *coordinates*, not the corners of the bounding
#' box: the `x_min` point carries the y value of whichever vertex was
#' leftmost. Use [bounding_rect()] for the envelope.
#'
#' @param x a GeoArrow geometry array
#' @returns an Arrow struct array of four point fields, with one row per geometry
#' @export
#' @family boundary
#' @references [Extremes](https://docs.rs/geo/latest/geo/algorithm/extremes/trait.Extremes.html)
extremes <- function(x) .Call(wrap__extremes, x)

#' Cast geometries to another GeoArrow geometry type
#'
#' Changes the geometry type of an array without changing the geometries it
#' holds.
#'
#' @details
#' Some casts always succeed:
#'
#' | from | to |
#' | --- | --- |
#' | `point` | `multipoint` |
#' | `linestring` | `multilinestring` |
#' | `polygon` | `multipolygon` |
#' | any type | `geometry`, `wkb`, `wkt` |
#'
#' Others are fallible and error when a geometry does not fit the target type,
#' such as a `multipoint` holding two points cast to `point`:
#'
#' | from | to |
#' | --- | --- |
#' | `multipoint` | `point` |
#' | `multilinestring` | `linestring` |
#' | `multipolygon` | `polygon` |
#' | `geometry` | any concrete type |
#'
#' The dimension is carried over from the input, and casting between different
#' dimensions is not supported.
#'
#' @param x a GeoArrow geometry array
#' @param to the target type, one of `"point"`, `"linestring"`, `"polygon"`,
#'   `"multipoint"`, `"multilinestring"`, `"multipolygon"`,
#'   `"geometrycollection"`, `"geometry"`, `"wkb"`, or `"wkt"`
#' @returns a GeoArrow array of the requested type, the same length as `x`
#' @export
#' @family cast
cast_geometry <- function(x, to) .Call(wrap__cast_geometry, x, to)

#' Cast geometries to the narrowest type that fits them
#'
#' Inspects the geometries and casts to the most specific type that can hold
#' every one of them. A `geometry` array holding only points becomes a `point`
#' array; one holding points and polygons is left alone, since no narrower
#' type fits.
#'
#' This is the inverse of casting up to `geometry`, and is useful after
#' reading a format that does not record a single geometry type.
#'
#' @param x a GeoArrow geometry array
#' @returns a GeoArrow array of the narrowest type that fits, the same length as `x`
#' @export
#' @family cast
downcast_geometry <- function(x) .Call(wrap__downcast_geometry, x)

#' Split multi-part geometries into their parts
#'
#' Returns a list the same length as the input, where each element is an array
#' of that geometry's constituent parts. A multipolygon of three polygons
#' becomes one element holding a polygon array of length three.
#'
#' @details
#' The output geometry type is the singular form of the input:
#'
#' | input | element type |
#' | --- | --- |
#' | `multipoint`, `point` | `point` |
#' | `multilinestring`, `linestring` | `linestring` |
#' | `multipolygon`, `polygon` | `polygon` |
#'
#' The element type is decided by the array's declared type, not by its
#' contents, so an array of multipolygons that all happen to hold one part
#' still explodes to polygons. A mixed `geometry` array has no single singular
#' type and errors; narrow it with [downcast_geometry()] first.
#'
#' A singular geometry yields an element of length one, so the operation is
#' well defined for any input. A null geometry yields a null element, which is
#' distinct from an empty one.
#'
#' Because the length is preserved, the result lines up with the row it came
#' from and can sit alongside the other columns of a table. Use [flatten()] to
#' collapse it into a single array with one row per part.
#'
#' @param x a GeoArrow geometry array
#' @returns a list array of the same length as `x`, whose elements are GeoArrow arrays
#' @export
#' @family cast
explode <- function(x) .Call(wrap__explode, x)

#' Collapse a list of geometries into a single array
#'
#' The inverse of [explode()]. Concatenates every element's parts into one
#' array, so a list of `n` elements holding `m` parts in total becomes an
#' array of length `m`.
#'
#' Null elements contribute nothing, so the result is shorter than the input
#' whenever an element holds more or fewer than one geometry.
#'
#' @param x a list array of GeoArrow arrays, as returned by [explode()]
#' @returns a GeoArrow array holding every part, flattened
#' @export
#' @family cast
flatten <- function(x) .Call(wrap__flatten, x)

#' Convert coordinates from radians to degrees
#'
#' Multiplies every x and y coordinate by `180 / pi`. The geometry type of the
#' output matches the geometry type of the input.
#'
#' @details
#' Only the x and y coordinates are converted. Z and M values are dropped,
#' since the conversion goes through a two dimensional representation.
#'
#' @param geometry a GeoArrow geometry array
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family convert
#' @references [ToDegrees](https://docs.rs/geo/latest/geo/algorithm/convert_angle_unit/trait.ToDegrees.html)
to_degrees <- function(geometry) .Call(wrap__to_degrees, geometry)

#' Convert coordinates from degrees to radians
#'
#' Multiplies every x and y coordinate by `pi / 180`. The geometry type of the
#' output matches the geometry type of the input.
#'
#' @details
#' Only the x and y coordinates are converted. Z and M values are dropped,
#' since the conversion goes through a two dimensional representation.
#'
#' @param geometry a GeoArrow geometry array
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family convert
#' @references [ToRadians](https://docs.rs/geo/latest/geo/algorithm/convert_angle_unit/trait.ToRadians.html)
to_radians <- function(geometry) .Call(wrap__to_radians, geometry)

#' Add intermediate points to geometries so no segment exceeds a maximum length
#'
#' Densifies linestrings, multilinestrings, polygons, and multipolygons by
#' inserting additional points along each segment until no segment exceeds
#' `max_segment_length`. The metric determines how segment length is measured.
#'
#' @param geometry a GeoArrow linestring, multilinestring, polygon, or multipolygon array
#' @param max_segment_length the maximum segment length; either length 1 or the same length as `geometry`
#' @param metric one of `"euclidean"`, `"haversine"`, `"geodesic"`, or `"rhumb"`
#' @returns a GeoArrow array of the same geometry type as the input
#' @export
#' @family densify
#' @references [Densifiable](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.Densifiable.html)
densify <- function(geometry, max_segment_length, metric) .Call(wrap__densify, geometry, max_segment_length, metric)

#' Interpolate a point along a linestring
#'
#' Returns the point at a given ratio or distance along each linestring,
#' measured from either the start or end. The metric determines how distance
#' is calculated.
#'
#' @param line a GeoArrow linestring array
#' @param value a numeric vector of ratio or distance values; length 1 or the same length as `line`
#' @param metric one of `"euclidean"`, `"haversine"`, `"geodesic"`, or `"rhumb"`
#' @param measure one of `"ratio"` or `"distance"`
#' @param from one of `"start"` or `"end"`
#' @returns a GeoArrow point array
#' @export
#' @family interpolate
#' @references [InterpolateLine](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.InterpolateLine.html)
interpolate_point <- function(line, value, metric, measure, from) .Call(wrap__interpolate_point, line, value, metric, measure, from)

#' Interpolate a point at a given distance between two points
#'
#' Returns the point located at `distance` along the path from `start` to `end`.
#' The metric determines how distance is measured.
#'
#' @param start a GeoArrow point array of start points
#' @param end a GeoArrow point array of end points
#' @param distance a numeric vector of distances; length 1 or the same length as `start`
#' @param metric one of `"euclidean"`, `"haversine"`, `"geodesic"`, or `"rhumb"`
#' @returns a GeoArrow point array
#' @export
#' @rdname interpolate_between
#' @family interpolate
#' @references [InterpolatePoint](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.InterpolatePoint.html)
point_at_distance_between <- function(start, end, distance, metric) .Call(wrap__point_at_distance_between, start, end, distance, metric)

#' Interpolate a point at a given ratio between two points
#'
#' Returns the point located at `ratio` of the way from `start` to `end`,
#' where 0.0 is the start and 1.0 is the end. The metric determines how
#' the interpolation is computed.
#'
#' @param start a GeoArrow point array of start points
#' @param end a GeoArrow point array of end points
#' @param ratio a numeric vector of ratios between 0 and 1; length 1 or the same length as `start`
#' @param metric one of `"euclidean"`, `"haversine"`, `"geodesic"`, or `"rhumb"`
#' @returns a GeoArrow point array
#' @export
#' @rdname interpolate_between
#' @family interpolate
#' @references [InterpolatePoint](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.InterpolatePoint.html)
point_at_ratio_between <- function(start, end, ratio, metric) .Call(wrap__point_at_ratio_between, start, end, ratio, metric)

#' Generate points at regular intervals along the line between two points
#'
#' Returns a multipoint array where each element contains all points spaced
#' at most `max_distance` apart along the path from `start` to `end`.
#'
#' @param start a GeoArrow point array of start points
#' @param end a GeoArrow point array of end points
#' @param max_distance the maximum spacing between generated points; length 1 or the same length as `start`
#' @param include_ends whether to include the start and end points in the output
#' @param metric one of `"euclidean"`, `"haversine"`, `"geodesic"`, or `"rhumb"`
#' @returns a GeoArrow multipoint array
#' @export
#' @family interpolate
#' @references [InterpolatePoint](https://docs.rs/geo/latest/geo/algorithm/line_measures/trait.InterpolatePoint.html)
points_along_line <- function(start, end, max_distance, include_ends, metric) .Call(wrap__points_along_line, start, end, max_distance, include_ends, metric)

#' Read a FlatGeobuf file into a record batch stream
#'
#' Reads the geometries together with the feature properties. Unlike the
#' shapefile and GeoJSON readers this one streams, so the whole file is never
#' held in memory at once.
#'
#' @details
#' The geometry type and the property schema are taken from the file header.
#' If the header carries no column information, up to 1000 features are scanned
#' to infer one.
#'
#' Passing `bbox` uses the file's packed Hilbert R-tree index to skip features
#' that fall outside it, so a spatial subset does not read the whole file.
#'
#' Features come back in the order the file stores them, which for an indexed
#' file is Hilbert R-tree order rather than the order they were written in.
#'
#' @param path path to a `.fgb` file.
#' @param bbox optionally a length 4 numeric vector of `c(xmin, ymin, xmax, ymax)`
#'   used to filter features spatially. `NULL` reads every feature.
#' @returns a `nanoarrow_array_stream` of record batches, holding the property
#'   columns followed by a `geometry` column.
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' path <- tempfile(fileext = ".fgb")
#' sf::st_write(sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE),
#'              path, quiet = TRUE)
#'
#' df <- as.data.frame(read_flatgeobuf(path))
#' dim(df)
#'
#' # only the features intersecting the box
#' nrow(as.data.frame(read_flatgeobuf(path, c(-79, 35, -78, 36))))
#' @export
#' @family io
read_flatgeobuf <- function(path, bbox = NULL) .Call(wrap__read_flatgeobuf, path, bbox)

#' Read a GeoJSON FeatureCollection into a record batch stream
#'
#' Reads the geometries together with the feature properties. Properties are
#' untyped in GeoJSON, so each column's arrow type is inferred by scanning
#' every feature.
#'
#' @details
#' The geometry column is narrowed to the most specific type that holds every
#' feature, promoting a singular type to its multi form where the two are
#' mixed. A feature with a `null` geometry becomes a null element and does not
#' affect the choice:
#'
#' | geometry types in the file | column type |
#' | --- | --- |
#' | all points | `geoarrow.point` |
#' | points and multipoints | `geoarrow.multipoint` |
#' | all polygons | `geoarrow.polygon` |
#' | polygons and multipolygons | `geoarrow.multipolygon` |
#' | more than one family, or any collection | `geoarrow.geometry` |
#'
#' Narrowing matters in practice: `geoarrow.geometry` is a dense union that
#' geoarrow's R bindings cannot yet convert, so a genuinely mixed collection
#' reads back as its raw storage rather than as geometries.
#'
#' Property columns appear in the order the keys are first seen. A key missing
#' from a given feature is null for that row. Types are widened across
#' features:
#'
#' | values seen for a key | column type |
#' | --- | --- |
#' | booleans | `Boolean` |
#' | integers | `Int64` |
#' | integers and reals | `Float64` |
#' | strings, or any mix that cannot unify | `Utf8` |
#' | only `null` | `Utf8`, all null |
#'
#' Nested arrays and objects have no arrow analogue and are kept as their raw
#' JSON text.
#'
#' Per RFC 7946 the coordinate reference system is always `OGC:CRS84`, so that
#' is set on the geometry column without reading anything from the file.
#'
#' @param path path to a `.geojson` file holding a `FeatureCollection`.
#' @returns a `nanoarrow_array_stream` of a single record batch, holding the
#'   property columns followed by a `geometry` column.
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' path <- tempfile(fileext = ".geojson")
#' sf::st_write(sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE),
#'              path, quiet = TRUE)
#'
#' df <- as.data.frame(read_geojson(path))
#' dim(df)
#' head(df[, c("NAME", "BIR74", "geometry")], 3)
#' @export
#' @family io
read_geojson <- function(path) .Call(wrap__read_geojson, path)

#' Read an ESRI Shapefile into a record batch stream
#'
#' Reads the `.shp` geometries together with the `.dbf` attributes. The CRS is
#' taken from the sibling `.prj` file when one is present.
#'
#' @details
#' Polylines are read as multilinestrings and polygons as multipolygons,
#' because a shapefile record of either type may contain multiple parts.
#'
#' The coordinate dimension is chosen once per file, from the shape type and
#' from whether the coordinates actually carry measures. A `PolygonZ` file with
#' no measures is therefore read as XYZ, rather than as XYZM full of nulls.
#'
#' | shape type | measures present | dimension |
#' | --- | --- | --- |
#' | `Point`, `Polyline`, `Polygon`, `Multipoint` | not applicable | XY |
#' | `PointM`, `PolylineM`, `PolygonM`, `MultipointM` | no | XY |
#' | `PointM`, `PolylineM`, `PolygonM`, `MultipointM` | yes | XYM |
#' | `PointZ`, `PolylineZ`, `PolygonZ`, `MultipointZ` | no | XYZ |
#' | `PointZ`, `PolylineZ`, `PolygonZ`, `MultipointZ` | yes | XYZM |
#'
#' If only some coordinates carry a measure, M is dropped and a message is
#' emitted, because an Arrow column cannot mix dimensions.
#'
#' `Multipatch` files are not supported.
#'
#' @param path path to a `.shp` file. The sibling `.dbf` and `.prj` files are
#'   resolved from the same base name.
#' @returns a `nanoarrow_array_stream` of a single record batch, holding the
#'   `.dbf` attribute columns followed by a `geometry` column.
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' path <- system.file("shape/nc.shp", package = "sf")
#' df <- as.data.frame(read_shapefile(path))
#'
#' # the .dbf attribute columns, followed by `geometry`
#' dim(df)
#' head(df[, c("NAME", "BIR74", "geometry")], 3)
#' @export
#' @family io
read_shapefile <- function(path) .Call(wrap__read_shapefile, path)

#' Test whether geometries are well formed
#'
#' `TRUE` when a geometry satisfies the OGC simple features rules.
#'
#' @details
#' Several algorithms give wrong answers on invalid input rather than failing,
#' so this is worth checking before trusting a result. Common problems are a
#' polygon whose rings self intersect, a ring with too few points, and a
#' coordinate that is `NaN` or infinite.
#'
#' A null geometry gives `NA`. Use [validation_error()] to see why a geometry
#' failed.
#'
#' @param geometry a GeoArrow geometry array
#' @returns a boolean array of the same length as `geometry`
#' @export
#' @rdname validation
#' @family validation
#' @references [Validation](https://docs.rs/geo/latest/geo/algorithm/validation/trait.Validation.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' good <- sf::st_polygon(list(matrix(
#'   c(0, 0, 2, 0, 2, 2, 0, 2, 0, 0), ncol = 2, byrow = TRUE
#' )))
#' bowtie <- sf::st_polygon(list(matrix(
#'   c(0, 0, 2, 2, 2, 0, 0, 2, 0, 0), ncol = 2, byrow = TRUE
#' )))
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(good, bowtie))
#'
#' as.vector(nanoarrow::convert_array(is_valid(g)))
#' as.vector(nanoarrow::convert_array(validation_error(g)))
is_valid <- function(geometry) .Call(wrap__is_valid, geometry)

#' Explain why a geometry is invalid
#'
#' Returns the first validation problem found, or `NA` when the geometry is
#' valid.
#'
#' @details
#' A geometry can break more than one rule; only the first is reported, since
#' fixing it often resolves the rest.
#'
#' @inheritParams is_valid
#' @returns a string array of the same length as `geometry`
#' @export
#' @rdname validation
#' @family validation
#' @references [Validation](https://docs.rs/geo/latest/geo/algorithm/validation/trait.Validation.html)
validation_error <- function(geometry) .Call(wrap__validation_error, geometry)

#' Compute Voronoi cells from the vertices of geometries
#'
#' Returns one multipolygon per input geometry, whose parts are the Voronoi
#' cells of that geometry's vertices. The output has the same length as the
#' input.
#'
#' @details
#' Every vertex of a geometry is treated as a site, so a multipoint of `k`
#' points yields `k` cells. A Voronoi diagram is unbounded, so the cells are
#' clipped: `"padded"` uses a box with 50 percent padding around the sites,
#' matching PostGIS `ST_VoronoiPolygons`, and `"envelope"` uses their exact
#' bounding box. Passing `boundary` clips to an arbitrary polygon instead,
#' which is the usual way to cut a diagram to a study area.
#'
#' A geometry with fewer than two distinct vertices, or one whose vertices are
#' all collinear, has no cells and comes back as an empty multipolygon rather
#' than a null. Use [voronoi_edges()] for the collinear case, which returns
#' the perpendicular bisectors. A null geometry stays null.
#'
#' @param geometry a GeoArrow geometry array whose vertices are the sites
#' @param clip how to bound the diagram, either `"padded"` or `"envelope"`.
#'   Ignored when `boundary` is supplied
#' @param tolerance sites closer together than this are snapped to the same
#'   position; length 1 or the same length as `geometry`
#' @param boundary an optional GeoArrow polygon array to clip to; length 1 or
#'   the same length as `geometry`
#' @returns a GeoArrow multipolygon array of the same length as `geometry`
#' @export
#' @family voronoi
#' @references [Voronoi](https://docs.rs/geo/latest/geo/algorithm/voronoi/trait.Voronoi.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' pts <- sf::st_multipoint(cbind(c(0, 1, 1, 0), c(0, 0, 1, 1)))
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(pts))
#'
#' cells <- voronoi_cells(g)
#' lengths(sf::st_as_sfc(geoarrow::as_geoarrow_vctr(cells)))
voronoi_cells <- function(geometry, clip = "padded", tolerance = 0, boundary = NULL) .Call(wrap__voronoi_cells, geometry, clip, tolerance, boundary)

#' Compute Voronoi edges from the vertices of geometries
#'
#' Returns one multilinestring per input geometry, whose parts are the
#' boundaries between that geometry's Voronoi cells. The output has the same
#' length as the input.
#'
#' @details
#' Unlike [voronoi_cells()], this works on collinear sites, where the edges
#' are the perpendicular bisectors between neighbouring points. Prefer it
#' when you want the diagram's skeleton rather than closed regions.
#'
#' A geometry with fewer than two distinct vertices has no edges and comes
#' back as an empty multilinestring. A null geometry stays null.
#'
#' @inheritParams voronoi_cells
#' @returns a GeoArrow multilinestring array of the same length as `geometry`
#' @export
#' @family voronoi
#' @references [Voronoi](https://docs.rs/geo/latest/geo/algorithm/voronoi/trait.Voronoi.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' pts <- sf::st_multipoint(cbind(c(0, 1, 1, 0), c(0, 0, 1, 1)))
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(pts))
#'
#' sf::st_as_sfc(geoarrow::as_geoarrow_vctr(voronoi_edges(g)))
voronoi_edges <- function(geometry, clip = "padded", tolerance = 0, boundary = NULL) .Call(wrap__voronoi_edges, geometry, clip, tolerance, boundary)

#' Apply a winding direction to polygon rings
#'
#' Rewinds each polygon so its exterior and interior rings follow a
#' consistent direction. The geometry type of the output matches the input.
#'
#' @details
#' `"default"` gives a counter-clockwise exterior ring and clockwise interior
#' rings, which is the winding the OGC simple features and GeoJSON
#' specifications call for. `"reversed"` gives the opposite. `"ccw"` and
#' `"cw"` are accepted as aliases and refer to the exterior ring.
#'
#' Rewinding does not change which points a polygon covers, only the order
#' its coordinates are stored in. A null geometry stays null.
#'
#' @param geometry a GeoArrow polygon or multipolygon array
#' @param direction one of `"default"`, `"reversed"`, `"ccw"`, or `"cw"`
#' @returns a GeoArrow array of the same geometry type as `geometry`
#' @export
#' @family winding
#' @references [Orient](https://docs.rs/geo/latest/geo/algorithm/orient/trait.Orient.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' # a clockwise square
#' p <- sf::st_polygon(list(matrix(
#'   c(0, 0, 0, 1, 1, 1, 1, 0, 0, 0), ncol = 2, byrow = TRUE
#' )))
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(p))
#'
#' winding_order(g)
#' winding_order(orient(g, "default"))
orient <- function(geometry, direction = "default") .Call(wrap__orient, geometry, direction)

#' Determine the winding order of a ring
#'
#' Returns `"clockwise"` or `"counterclockwise"` for each geometry. A polygon
#' reports the winding of its exterior ring.
#'
#' @details
#' A multipolygon reports a winding only when every part's exterior ring
#' agrees, and a multilinestring only when every part agrees; a geometry whose
#' parts disagree is `NA`, since it has no single winding. Any other geometry
#' type, a null geometry, or a ring with fewer than three distinct points is
#' also `NA`.
#'
#' @param geometry a GeoArrow linestring, polygon, or multi part array of either
#' @returns a string array of the same length as `geometry`
#' @export
#' @family winding
#' @references [Winding](https://docs.rs/geo/latest/geo/algorithm/winding_order/trait.Winding.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' ring <- matrix(c(0, 0, 0, 1, 1, 1, 1, 0, 0, 0), ncol = 2, byrow = TRUE)
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_polygon(list(ring))))
#'
#' as.vector(nanoarrow::convert_array(winding_order(g)))
winding_order <- function(geometry) .Call(wrap__winding_order, geometry)

#' Test the winding order of a ring
#'
#' `is_ccw()` is `TRUE` for counter-clockwise geometries and `is_cw()` is
#' `TRUE` for clockwise ones. A polygon is tested on its exterior ring.
#'
#' @details
#' Any geometry with no winding order, such as a point or a null geometry,
#' becomes `NA` rather than `FALSE`, so the two functions are not simply
#' negations of one another.
#'
#' @param geometry a GeoArrow linestring or polygon array
#' @returns a boolean array of the same length as `geometry`
#' @export
#' @rdname is_ccw
#' @family winding
#' @references [Winding](https://docs.rs/geo/latest/geo/algorithm/winding_order/trait.Winding.html)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' ring <- matrix(c(0, 0, 0, 1, 1, 1, 1, 0, 0, 0), ncol = 2, byrow = TRUE)
#' g <- geoarrow::as_geoarrow_array(sf::st_sfc(sf::st_polygon(list(ring))))
#'
#' as.vector(nanoarrow::convert_array(is_ccw(g)))
#' as.vector(nanoarrow::convert_array(is_cw(orient(g, "reversed"))))
is_ccw <- function(geometry) .Call(wrap__is_ccw, geometry)

#' @export
#' @rdname is_ccw
#' @family winding
is_cw <- function(geometry) .Call(wrap__is_cw, geometry)

#' A packed Hilbert R-tree over the bounding boxes of a geometry array.
#' A spatial index over a geometry array
#'
#' Indexes the bounding box of each geometry so that queries can skip the rows
#' that cannot match.
#'
#' @details
#' The tree is a packed Hilbert R-tree, the same structure FlatGeobuf stores
#' on disk. It is built once and is immutable, so it pays off when a set of
#' geometries is queried repeatedly.
#'
#' Every query is a bounding box test, not an exact one. Two geometries whose
#' boxes overlap need not themselves intersect, so treat results as candidates
#' and confirm with [intersects()] when exactness matters. Narrowing to
#' candidates first is the point: the exact test then runs on a handful of
#' rows rather than all of them.
#'
#' Rows with a null or empty geometry have no bounding box and are left out of
#' the tree, so a query never returns them. Row numbers always refer to
#' positions in the original array.
#'
#' @returns an `RTree` object
#' @export
#' @family index
#' @references [geo-index](https://docs.rs/geo-index/latest/geo_index/)
#' @examplesIf requireNamespace("sf", quietly = TRUE) && requireNamespace("geoarrow", quietly = TRUE)
#' nc <- as.data.frame(read_shapefile(
#'   system.file("shape/nc.shp", package = "sf")
#' ))
#' idx <- RTree$new(nc$geometry)
#'
#' idx$size()
#'
#' # candidate rows whose bounding box meets the query box
#' hits <- as.vector(nanoarrow::convert_array(idx$search(-79, 35, -78, 36)))
#' length(hits)
#'
#' # the three rows nearest a point
#' as.vector(nanoarrow::convert_array(idx$neighbors(-79, 35, max_results = 3)))
#' @section Methods:
#'\subsection{Method `new`}{
#'Build the index. `node_size` sets how many entries share a tree node;
#'larger values build faster and query slower.
#'}
#'
#'\subsection{Method `search`}{
#'Find the rows whose bounding box overlaps a query box
#'
#'Returns the row numbers whose bounding box intersects the given box,
#'in increasing order.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`xmin,ymin,xmax,ymax`}{the query box}
#'}}
#' \subsection{details}{
#'This is a bounding box test, not an exact one. Two geometries whose
#'boxes overlap need not themselves intersect, so treat the result as a
#'set of candidates and confirm with [intersects()] when exactness
#'matters.
#'
#'}
#' \subsection{returns}{
#'an integer array of 1 based row numbers
#'}
#' \subsection{export}{
#'
#'}
#' \subsection{family}{
#'index
#'}
#'}
#'
#'\subsection{Method `neighbors`}{
#'Find the rows nearest a point
#'
#'Returns row numbers ordered by how close their bounding box is to the
#'point.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`x,y`}{the query point}
#'\item{`max_results`}{the most rows to return, or `NULL` for no limit}
#'\item{`max_distance`}{the furthest to search, or `NULL` for no limit}
#'}}
#' \subsection{details}{
#'Distance is measured to the bounding box rather than to the geometry
#'itself, so this too gives candidates. `max_results` caps how many come
#'back and `max_distance` caps how far the search goes; either can be
#'`NULL`.
#'
#'}
#' \subsection{returns}{
#'an integer array of 1 based row numbers
#'}
#' \subsection{export}{
#'
#'}
#' \subsection{family}{
#'index
#'}
#'}
#'
#'\subsection{Method `size`}{
#'The number of rows the index was built over
#'
#' \subsection{returns}{
#'the length of the array the index was built from
#'}
#' \subsection{export}{
#'
#'}
#' \subsection{family}{
#'index
#'}
#'}
#'
#'\subsection{Method `n_indexed`}{
#'The number of rows actually held in the tree
#'
#' \subsection{details}{
#'Lower than `size()` when the array held null or empty geometries, which
#'have no bounding box to index.
#'
#'}
#' \subsection{returns}{
#'the number of indexed rows
#'}
#' \subsection{export}{
#'
#'}
#' \subsection{family}{
#'index
#'}
#'}
#'
RTree <- new.env(parent = emptyenv())

RTree$new <- function(geometry, node_size = 16) .Call(wrap__RTree__new, geometry, node_size)

RTree$search <- function(xmin, ymin, xmax, ymax) .Call(wrap__RTree__search, self, xmin, ymin, xmax, ymax)

RTree$neighbors <- function(x, y, max_results = NULL, max_distance = NULL) .Call(wrap__RTree__neighbors, self, x, y, max_results, max_distance)

RTree$size <- function() .Call(wrap__RTree__size, self)

RTree$n_indexed <- function() .Call(wrap__RTree__n_indexed, self)

#' @rdname RTree
#' @usage NULL
#' @export
`$.RTree` <- function (self, name) { func <- RTree[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RTree` <- `$.RTree`

# nolint end
